### PR TITLE
Fix minor yellow line at display

### LINKED ISSUE #196: [PE-D][Tester A] Feature flaw of the app (display issue)
When a person is added without a rating, it is shown as a minor yellow line under the person.

An example is given below as shown for the person in the 7th index.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: L1uY1jun/ped#13

### PR DESCRIPTION
**Pull request by ytingtan**
Closes #196

### CODE REVIEW

File: src/main/java/seedu/clinkedin/ui/PersonCard.java [hunk 1]
```diff
@@ -123,7 +123,9 @@ public PersonCard(Person person, int displayedIndex, MainWindow mainWindow) {
         rating.setPadding(new Insets(1));
 
         CornerRadii corn = new CornerRadii(2.5);
-        if (ratingNumber <= 3 && ratingNumber >= 1) {
+        if (ratingNumber == 0) {
+            // do not show anything
```
Comment (Josephaedan) [inline src/main/java/seedu/clinkedin/ui/PersonCard.java:127]: Might be bad code practice to just have empty clauses. Are you able to somehow refactor this/remove this clause while making the logic intact?

**Review by Josephaedan — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/clinkedin/ui/PersonCard.java (hunk 1 above)
Comment (ytingtan) [reply src/main/java/seedu/clinkedin/ui/PersonCard.java:127]: ok

**Review by Josephaedan — APPROVED** [review]
LGTM, thanks for changing the logic!
